<h1>K-NN</h1>
<p>This project uses the K-NN algorithm to predict the class of vehicles based off other atributes</p> <p>K-NN or K-nearest neighbor is a supervised learning algorithm which groups similar datapoints where k represents the number of groups and then uses these groupings to make predictions about new data</p>

In [1]:
# Libraries
import sklearn
from sklearn.utils import shuffle
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
from sklearn import linear_model, preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("car.data", sep=",")
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [3]:
#data preprocessing
le = preprocessing.LabelEncoder()
buying = le.fit_transform(list(data["buying"]))
maint = le.fit_transform(list(data["maint"]))
doors = le.fit_transform(list(data["doors"]))
persons = le.fit_transform(list(data["persons"]))
lug_boot = le.fit_transform(list(data["lug_boot"]))
safety = le.fit_transform(list(data["safety"]))
cls = le.fit_transform(list(data["class"]))

In [4]:
#x will be data used to predict
x = list (zip(buying, maint, doors, persons, lug_boot, safety))
#y will be variable that is predicted
y = list(cls)

#seperates the data into seperate training and testing data, the model is trained on x_train and y_train and then predicts y_test using x_test
x_train, x_test, y_train, y_test, = sklearn.model_selection.train_test_split(x,y, test_size=0.1)
print(x_train, y_test)

[(1, 1, 0, 1, 2, 2), (1, 0, 0, 2, 1, 0), (1, 1, 3, 0, 0, 1), (3, 2, 0, 2, 0, 1), (1, 2, 1, 1, 1, 1), (3, 2, 2, 0, 1, 1), (3, 3, 0, 2, 1, 2), (3, 0, 3, 2, 1, 1), (0, 0, 0, 2, 1, 0), (3, 3, 3, 0, 0, 2), (1, 0, 3, 1, 2, 2), (1, 2, 1, 1, 0, 0), (2, 3, 2, 0, 1, 2), (3, 0, 3, 2, 1, 2), (3, 0, 1, 0, 1, 0), (0, 0, 3, 2, 1, 0), (1, 0, 3, 0, 1, 2), (2, 1, 0, 1, 2, 1), (0, 2, 2, 0, 1, 1), (2, 2, 3, 1, 2, 0), (3, 0, 2, 0, 0, 0), (2, 3, 1, 2, 0, 0), (2, 1, 1, 0, 1, 1), (2, 2, 2, 2, 0, 1), (1, 1, 2, 1, 0, 0), (1, 3, 3, 1, 2, 0), (1, 3, 2, 1, 1, 2), (1, 0, 2, 1, 1, 0), (2, 2, 0, 1, 0, 1), (1, 3, 1, 1, 0, 2), (0, 1, 0, 1, 2, 1), (3, 2, 1, 1, 1, 0), (1, 3, 1, 1, 1, 2), (1, 2, 0, 0, 1, 0), (1, 0, 0, 0, 1, 1), (2, 3, 3, 2, 2, 1), (0, 2, 1, 2, 0, 0), (1, 2, 3, 2, 0, 2), (2, 1, 2, 2, 0, 1), (0, 0, 3, 0, 2, 1), (3, 1, 1, 0, 0, 0), (0, 0, 1, 2, 2, 2), (3, 1, 0, 0, 2, 1), (2, 2, 2, 0, 0, 2), (0, 3, 3, 1, 0, 1), (0, 1, 2, 1, 2, 0), (3, 3, 0, 0, 0, 0), (2, 2, 2, 2, 1, 2), (1, 0, 0, 2, 0, 1), (2, 2, 2, 0, 1, 2),

In [5]:
#creates a new KNN object
model = KNeighborsClassifier(metric='euclidean', p=3,  n_neighbors=9)
#trains model
model.fit(x_train, y_train)

#prints model accuracy as a percentage in decimal form
acc = model.score(x_test, y_test)
print(acc)

0.930635838150289


In [6]:
#attempts to predict y_test with X_test
y_pred = model.predict(x_test)
y_pred

array([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2,
       2, 2, 2, 2, 2, 3, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 0, 0, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 0, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2,
       2, 2, 0, 2, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 3, 2, 1, 0,
       2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2])

In [7]:
predicted = model.predict(x_test)
names = ["unnac", "acc", "good", "vgood"]
#compares the predicted class with the actual class
for x in range (len(predicted)):
    print ("predicted: ", names[predicted[x]], "Data:", x_test[x], "actual:",names[y_test[x]])
    n = model.kneighbors([x_test[x]], 9, True)
print("N:", n)

predicted:  unnac Data: (1, 3, 1, 2, 1, 0) actual: unnac
predicted:  good Data: (2, 1, 1, 2, 2, 2) actual: unnac
predicted:  good Data: (2, 0, 3, 1, 1, 1) actual: good
predicted:  good Data: (2, 1, 1, 0, 0, 2) actual: good
predicted:  good Data: (3, 0, 3, 0, 0, 2) actual: good
predicted:  good Data: (0, 3, 3, 2, 0, 0) actual: good
predicted:  good Data: (3, 0, 1, 2, 0, 2) actual: good
predicted:  good Data: (1, 3, 0, 2, 1, 1) actual: good
predicted:  good Data: (0, 2, 1, 1, 2, 1) actual: good
predicted:  good Data: (2, 1, 2, 0, 0, 2) actual: good
predicted:  good Data: (2, 0, 3, 0, 1, 2) actual: good
predicted:  unnac Data: (2, 2, 0, 2, 0, 2) actual: unnac
predicted:  good Data: (1, 2, 3, 0, 1, 2) actual: good
predicted:  good Data: (0, 0, 1, 0, 0, 0) actual: good
predicted:  good Data: (2, 1, 2, 1, 1, 1) actual: good
predicted:  good Data: (1, 3, 2, 0, 2, 0) actual: good
predicted:  good Data: (3, 1, 1, 0, 1, 0) actual: good
predicted:  good Data: (2, 0, 0, 0, 2, 0) actual: good
predi

In [8]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[ 26   0   8   0]
 [  0   5   1   0]
 [  1   0 125   0]
 [  1   1   0   5]]
0.930635838150289
